# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_event', models.CharField(max_length=255, verbose_name='Type of event')),
                ('description', models.TextField(verbose_name='Description of event')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2016, 4, 23, 16, 11, 9, 598209, tzinfo=utc), verbose_name='Start date of event')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='(Optional) end date for event')),
                ('places_close_by', models.TextField(verbose_name='Interesting/useful places (e.g shops) nearby')),
                ('things_to_take_note_of', models.TextField(verbose_name='Things to take note of (e.g existing debts for you cheapskates)')),
                ('extra_information', models.TextField(verbose_name='Additional information')),
                ('sum_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price of event in total')),
                ('entry_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price for entering')),
                ('attendees', models.ManyToManyField(related_name='attending', to='users.UserProfile')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.UserProfile')),
                ('people_needing_a_ride', models.ManyToManyField(related_name='needs_ride_for', to='users.UserProfile')),
                ('people_offering_rides', models.ManyToManyField(related_name='offering_rides_for', to='users.UserProfile')),
            ],
        ),
    ]
